using System;
using Swashbuckle.AspNetCore.Annotations;

namespace Redoc.Api.Models
{
    public class BaseResponse
    {
        [SwaggerSchema(Description = "this is the one Id generated by the database for the entity.")]
        public int Id { get; set; }

        [SwaggerSchema(Description = "this is the entity creation date.")]
        public DateTime DataCreation { get; set; }
    }
}
